[tasks.gcp-set-project]
run = "gcloud config set project $PROJECT_ID && gcloud auth configure-docker asia-northeast1-docker.pkg.dev"

[tasks.image-push]
run = "docker build -t $IMAGE_URI . && docker push $IMAGE_URI"

[tasks.deploy]
run = "gcloud run deploy pdf-reader-api --image \"$IMAGE_URI\" --region asia-northeast1 --project \"$PROJECT_ID\" --platform managed --allow-unauthenticated"
